// The AI Engineering Brain — project knowledge graph
// Import into Neo4j (AuraDB Free or Community):  cat graph.cypher | cypher-shell
MATCH (n:Chapter|Tool|Concept) DETACH DELETE n;

CREATE (:Chapter {id: 'c1', name: "Ch 1 — Executive Summary", url: "../chapters/01-executive-summary.md"});
CREATE (:Chapter {id: 'c2', name: "Ch 2 — Evolution", url: "../chapters/02-evolution-of-ai-software-engineering.md"});
CREATE (:Chapter {id: 'c3', name: "Ch 3 — Prompt → Knowledge", url: "../chapters/03-prompt-to-knowledge-engineering.md"});
CREATE (:Chapter {id: 'c4', name: "Ch 4 — Why RAG Isn't Enough", url: "../chapters/04-why-rag-isnt-enough.md"});
CREATE (:Chapter {id: 'c5', name: "Ch 5 — Knowledge Graphs", url: "../chapters/05-knowledge-graphs.md"});
CREATE (:Chapter {id: 'c6', name: "Ch 6 — GraphRAG", url: "../chapters/06-graphrag.md"});
CREATE (:Chapter {id: 'c7', name: "Ch 7 — Graphify", url: "../chapters/07-graphify.md"});
CREATE (:Chapter {id: 'c8', name: "Ch 8 — Graphiti", url: "../chapters/08-graphiti.md"});
CREATE (:Chapter {id: 'c9', name: "Ch 9 — Tree-sitter", url: "../chapters/09-tree-sitter.md"});
CREATE (:Chapter {id: 'c10', name: "Ch 10 — Neo4j & Qdrant", url: "../chapters/10-neo4j-and-qdrant.md"});
CREATE (:Chapter {id: 'c11', name: "Ch 11 — MCP & Agents", url: "../chapters/11-mcp-and-ai-agents.md"});
CREATE (:Chapter {id: 'c12', name: "Ch 12 — Production", url: "../chapters/12-costs-deployment-future.md"});
CREATE (:Chapter {id: 'c13', name: "Ch 13 — Compound Engineering", url: "../chapters/13-compound-engineering.md"});
CREATE (:Chapter {id: 'c14', name: "Ch 14 — Multi-Agent Systems", url: "../chapters/14-multi-agent-systems.md"});
CREATE (:Chapter {id: 'c15', name: "Ch 15 — Virtual Organizations", url: "../chapters/15-virtual-organizations.md"});
CREATE (:Chapter {id: 'c16', name: "Ch 16 — Spec-Driven Development", url: "../chapters/16-spec-driven-development.md"});
CREATE (:Chapter {id: 'c17', name: "Ch 17 — Git Worktrees", url: "../chapters/17-git-worktrees.md"});
CREATE (:Chapter {id: 'c18', name: "Ch 18 — Sprint Tracking", url: "../chapters/18-sprint-tracking.md"});
CREATE (:Chapter {id: 'cA', name: "Appendix — Tool Directory", url: "../appendix/tool-directory.md"});
CREATE (:Tool {id: 'graphify', name: "Graphify", url: "https://github.com/safishamsi/graphify"});
CREATE (:Tool {id: 'graphiti', name: "Graphiti", url: "https://github.com/getzep/graphiti"});
CREATE (:Tool {id: 'neo4j', name: "Neo4j", url: "https://neo4j.com"});
CREATE (:Tool {id: 'qdrant', name: "Qdrant", url: "https://qdrant.tech"});
CREATE (:Tool {id: 'treesitter', name: "Tree-sitter", url: "https://github.com/tree-sitter/tree-sitter"});
CREATE (:Tool {id: 'mcp', name: "MCP", url: "https://modelcontextprotocol.io"});
CREATE (:Tool {id: 'claudecode', name: "Claude Code", url: "https://claude.com/claude-code"});
CREATE (:Tool {id: 'codex', name: "Codex", url: "https://openai.com/codex/"});
CREATE (:Tool {id: 'cursor', name: "Cursor", url: "https://cursor.com"});
CREATE (:Tool {id: 'geminicli', name: "Gemini CLI", url: "https://github.com/google-gemini/gemini-cli"});
CREATE (:Tool {id: 'continue', name: "Continue", url: "https://continue.dev"});
CREATE (:Tool {id: 'opencode', name: "OpenCode", url: "https://github.com/sst/opencode"});
CREATE (:Tool {id: 'sourcegraph', name: "Sourcegraph", url: "https://sourcegraph.com"});
CREATE (:Tool {id: 'llamaindex', name: "LlamaIndex", url: "https://www.llamaindex.ai"});
CREATE (:Tool {id: 'deepwiki', name: "DeepWiki", url: "https://deepwiki.com"});
CREATE (:Tool {id: 'gitingest', name: "Gitingest", url: "https://gitingest.com"});
CREATE (:Tool {id: 'langgraph', name: "LangGraph", url: "https://github.com/langchain-ai/langgraph"});
CREATE (:Tool {id: 'git', name: "Git", url: "https://git-scm.com/docs/git-worktree"});
CREATE (:Tool {id: 'fork', name: "Fork", url: "https://git-fork.com"});
CREATE (:Concept {id: 'prompteng', name: "Prompt Engineering"});
CREATE (:Concept {id: 'contexteng', name: "Context Engineering"});
CREATE (:Concept {id: 'rag', name: "RAG"});
CREATE (:Concept {id: 'kg', name: "Knowledge Graph"});
CREATE (:Concept {id: 'graphrag', name: "GraphRAG"});
CREATE (:Concept {id: 'specdriven', name: "Spec-Driven Dev"});
CREATE (:Concept {id: 'memory', name: "Agent Memory"});
CREATE (:Concept {id: 'ast', name: "AST"});
CREATE (:Concept {id: 'embeddings', name: "Embeddings"});
CREATE (:Concept {id: 'propgraph', name: "Property Graph"});
CREATE (:Concept {id: 'compound', name: "Compound Engineering"});
CREATE (:Concept {id: 'orchestration', name: "Agent Orchestration"});
CREATE (:Concept {id: 'mas', name: "Multi-Agent System"});
CREATE (:Concept {id: 'vo', name: "Virtual Organization"});
CREATE (:Concept {id: 'worktree', name: "Git Worktree"});
CREATE (:Concept {id: 'sprinttrack', name: "Sprint Tracking"});
CREATE (:Concept {id: 'adr', name: "Decision Record"});

MATCH (a {id: 'c1'}), (b {id: 'c2'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c2'}), (b {id: 'c3'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c3'}), (b {id: 'c4'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c4'}), (b {id: 'c5'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c5'}), (b {id: 'c6'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c6'}), (b {id: 'c7'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c7'}), (b {id: 'c8'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c8'}), (b {id: 'c9'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c9'}), (b {id: 'c10'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c10'}), (b {id: 'c11'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c11'}), (b {id: 'c12'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c12'}), (b {id: 'c13'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c13'}), (b {id: 'c14'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c14'}), (b {id: 'c15'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c15'}), (b {id: 'c16'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c16'}), (b {id: 'c17'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c17'}), (b {id: 'c18'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c18'}), (b {id: 'cA'}) CREATE (a)-[:FOLLOWED_BY]->(b);
MATCH (a {id: 'c1'}), (b {id: 'kg'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c2'}), (b {id: 'rag'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c2'}), (b {id: 'graphrag'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c3'}), (b {id: 'prompteng'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c3'}), (b {id: 'contexteng'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c3'}), (b {id: 'specdriven'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c4'}), (b {id: 'rag'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c4'}), (b {id: 'embeddings'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c5'}), (b {id: 'kg'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c5'}), (b {id: 'propgraph'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c6'}), (b {id: 'graphrag'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c7'}), (b {id: 'graphify'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c8'}), (b {id: 'graphiti'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c8'}), (b {id: 'memory'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c9'}), (b {id: 'treesitter'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c9'}), (b {id: 'ast'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c10'}), (b {id: 'neo4j'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c10'}), (b {id: 'qdrant'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c11'}), (b {id: 'mcp'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c11'}), (b {id: 'claudecode'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c12'}), (b {id: 'graphify'}) CREATE (a)-[:RECOMMENDS]->(b);
MATCH (a {id: 'c12'}), (b {id: 'claudecode'}) CREATE (a)-[:RECOMMENDS]->(b);
MATCH (a {id: 'c13'}), (b {id: 'compound'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c14'}), (b {id: 'mas'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c14'}), (b {id: 'orchestration'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c15'}), (b {id: 'vo'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c16'}), (b {id: 'specdriven'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c17'}), (b {id: 'worktree'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c17'}), (b {id: 'git'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c17'}), (b {id: 'fork'}) CREATE (a)-[:RECOMMENDS]->(b);
MATCH (a {id: 'c18'}), (b {id: 'sprinttrack'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'c18'}), (b {id: 'adr'}) CREATE (a)-[:COVERS]->(b);
MATCH (a {id: 'cA'}), (b {id: 'sourcegraph'}) CREATE (a)-[:CATALOGS]->(b);
MATCH (a {id: 'cA'}), (b {id: 'llamaindex'}) CREATE (a)-[:CATALOGS]->(b);
MATCH (a {id: 'cA'}), (b {id: 'deepwiki'}) CREATE (a)-[:CATALOGS]->(b);
MATCH (a {id: 'cA'}), (b {id: 'gitingest'}) CREATE (a)-[:CATALOGS]->(b);
MATCH (a {id: 'cA'}), (b {id: 'langgraph'}) CREATE (a)-[:CATALOGS]->(b);
MATCH (a {id: 'cA'}), (b {id: 'continue'}) CREATE (a)-[:CATALOGS]->(b);
MATCH (a {id: 'graphify'}), (b {id: 'treesitter'}) CREATE (a)-[:USES]->(b);
MATCH (a {id: 'graphify'}), (b {id: 'kg'}) CREATE (a)-[:BUILDS]->(b);
MATCH (a {id: 'graphify'}), (b {id: 'neo4j'}) CREATE (a)-[:STORES_IN]->(b);
MATCH (a {id: 'graphiti'}), (b {id: 'neo4j'}) CREATE (a)-[:STORES_IN]->(b);
MATCH (a {id: 'graphiti'}), (b {id: 'memory'}) CREATE (a)-[:ENABLES]->(b);
MATCH (a {id: 'treesitter'}), (b {id: 'ast'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a {id: 'neo4j'}), (b {id: 'propgraph'}) CREATE (a)-[:IMPLEMENTS]->(b);
MATCH (a {id: 'qdrant'}), (b {id: 'embeddings'}) CREATE (a)-[:STORES]->(b);
MATCH (a {id: 'rag'}), (b {id: 'embeddings'}) CREATE (a)-[:USES]->(b);
MATCH (a {id: 'contexteng'}), (b {id: 'prompteng'}) CREATE (a)-[:EVOLVES_FROM]->(b);
MATCH (a {id: 'rag'}), (b {id: 'contexteng'}) CREATE (a)-[:IMPLEMENTS]->(b);
MATCH (a {id: 'specdriven'}), (b {id: 'contexteng'}) CREATE (a)-[:COMPLEMENTS]->(b);
MATCH (a {id: 'graphrag'}), (b {id: 'rag'}) CREATE (a)-[:COMBINES]->(b);
MATCH (a {id: 'graphrag'}), (b {id: 'kg'}) CREATE (a)-[:COMBINES]->(b);
MATCH (a {id: 'mcp'}), (b {id: 'neo4j'}) CREATE (a)-[:CONNECTS]->(b);
MATCH (a {id: 'mcp'}), (b {id: 'qdrant'}) CREATE (a)-[:CONNECTS]->(b);
MATCH (a {id: 'claudecode'}), (b {id: 'mcp'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a {id: 'codex'}), (b {id: 'mcp'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a {id: 'cursor'}), (b {id: 'mcp'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a {id: 'geminicli'}), (b {id: 'mcp'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a {id: 'continue'}), (b {id: 'mcp'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a {id: 'opencode'}), (b {id: 'mcp'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a {id: 'graphify'}), (b {id: 'claudecode'}) CREATE (a)-[:INTEGRATES_WITH]->(b);
MATCH (a {id: 'graphify'}), (b {id: 'cursor'}) CREATE (a)-[:INTEGRATES_WITH]->(b);
MATCH (a {id: 'graphify'}), (b {id: 'codex'}) CREATE (a)-[:INTEGRATES_WITH]->(b);
MATCH (a {id: 'llamaindex'}), (b {id: 'rag'}) CREATE (a)-[:IMPLEMENTS]->(b);
MATCH (a {id: 'sourcegraph'}), (b {id: 'kg'}) CREATE (a)-[:RELATED_TO]->(b);
MATCH (a {id: 'compound'}), (b {id: 'kg'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a {id: 'compound'}), (b {id: 'specdriven'}) CREATE (a)-[:BUILDS_ON]->(b);
MATCH (a {id: 'mas'}), (b {id: 'orchestration'}) CREATE (a)-[:USES]->(b);
MATCH (a {id: 'mas'}), (b {id: 'memory'}) CREATE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'mas'}), (b {id: 'mcp'}) CREATE (a)-[:USES]->(b);
MATCH (a {id: 'claudecode'}), (b {id: 'mas'}) CREATE (a)-[:IMPLEMENTS]->(b);
MATCH (a {id: 'vo'}), (b {id: 'mas'}) CREATE (a)-[:CONTAINS]->(b);
MATCH (a {id: 'vo'}), (b {id: 'memory'}) CREATE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'vo'}), (b {id: 'kg'}) CREATE (a)-[:USES]->(b);
MATCH (a {id: 'vo'}), (b {id: 'compound'}) CREATE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'specdriven'}), (b {id: 'compound'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a {id: 'specdriven'}), (b {id: 'mas'}) CREATE (a)-[:CONTRACTS]->(b);
MATCH (a {id: 'specdriven'}), (b {id: 'kg'}) CREATE (a)-[:MODELED_IN]->(b);
MATCH (a {id: 'git'}), (b {id: 'worktree'}) CREATE (a)-[:PROVIDES]->(b);
MATCH (a {id: 'fork'}), (b {id: 'worktree'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a {id: 'mas'}), (b {id: 'worktree'}) CREATE (a)-[:REQUIRES]->(b);
MATCH (a {id: 'vo'}), (b {id: 'worktree'}) CREATE (a)-[:USES]->(b);
MATCH (a {id: 'compound'}), (b {id: 'worktree'}) CREATE (a)-[:USES]->(b);
MATCH (a {id: 'worktree'}), (b {id: 'orchestration'}) CREATE (a)-[:COMPLEMENTS]->(b);
MATCH (a {id: 'worktree'}), (b {id: 'claudecode'}) CREATE (a)-[:ISOLATES]->(b);
MATCH (a {id: 'worktree'}), (b {id: 'specdriven'}) CREATE (a)-[:VERIFIES]->(b);
MATCH (a {id: 'graphify'}), (b {id: 'worktree'}) CREATE (a)-[:INDEXES]->(b);
MATCH (a {id: 'sprinttrack'}), (b {id: 'adr'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a {id: 'sprinttrack'}), (b {id: 'compound'}) CREATE (a)-[:IMPLEMENTS]->(b);
MATCH (a {id: 'sprinttrack'}), (b {id: 'specdriven'}) CREATE (a)-[:COMPLEMENTS]->(b);
MATCH (a {id: 'sprinttrack'}), (b {id: 'memory'}) CREATE (a)-[:ENABLES]->(b);
MATCH (a {id: 'adr'}), (b {id: 'kg'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a {id: 'adr'}), (b {id: 'propgraph'}) CREATE (a)-[:MODELED_IN]->(b);
MATCH (a {id: 'claudecode'}), (b {id: 'sprinttrack'}) CREATE (a)-[:MAINTAINS]->(b);

// Example queries
// Which chapters cover the recommended stack?
// MATCH (c:Chapter)-[:COVERS]->(t:Tool) RETURN c.name, t.name;
// What does Graphify connect to?
// MATCH (g:Tool {name:'Graphify'})-[r]-(x) RETURN g.name, type(r), x.name;

// --- Ch 18: the engineering record ---
// What does Sprint Tracking connect to?
// MATCH (s:Concept {name:'Sprint Tracking'})-[r]-(x) RETURN type(r), x.name;
// Which chapter should I read to learn about decision records?
// MATCH (c:Chapter)-[:COVERS]->(:Concept {name:'Decision Record'}) RETURN c.name, c.url;
// The Ch 18 thesis as a path: how does a decision reach the knowledge graph?
// MATCH p = (:Concept {name:'Sprint Tracking'})-[:PRODUCES]->()-[:FEEDS]->(:Concept {name:'Knowledge Graph'})
// RETURN [n IN nodes(p) | n.name] AS path;
// Which practices feed Compound Engineering, and how? (Ch 13 ← 16, 18)
// MATCH (x)-[r:IMPLEMENTS|BUILDS_ON|FEEDS]->(:Concept {name:'Compound Engineering'})
// RETURN x.name, type(r);
// Everything an agent is expected to maintain
// MATCH (t:Tool)-[:MAINTAINS]->(x) RETURN t.name, x.name;
